name: Table of contents

on:
  push:
    paths:
      - '.github/workflows/table-of-contents.yml'
      - 'docs/README.md'
  pull_request:
    paths:
      - '.github/workflows/table-of-contents.yml'
      - 'docs/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toc
        run: wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc && chmod a+x gh-md-toc
      - name: Generate toc
        run: ./gh-md-toc --insert ./docs/README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          labels: Documentation
          title: Update table of contents
          body: This is an automatic merge request
          branch: table-of-contents
          commit-message: Update table of contents