name: Unit tests

on:
  push:
    paths:
      - '.github/workflows/unittests.yml'
      - 'src/**'
      - 'tests/Unit/**'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
  pull_request:
    paths:
      - '.github/workflows/unittests.yml'
      - 'src/**'
      - 'tests/Unit/**'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Unit tests
      run: php -d zend.assertions=1 vendor/bin/phpunit --testsuite unit