name: Update dependencies

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Update dependencies
          body: This is an automatic merge request
          branch: update-dependencies
          commit-message: Update dependencies